apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/OWNER/gospel-library-web
    newName: ghcr.io/OWNER/gospel-library-web
    newTag: production
  - name: ghcr.io/OWNER/gospel-library-rag
    newName: ghcr.io/OWNER/gospel-library-rag
    newTag: production
  - name: ghcr.io/OWNER/gospel-library-scraper
    newName: ghcr.io/OWNER/gospel-library-scraper
    newTag: production

patches:
  - target:
      kind: Deployment
      name: rag-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
