from app.db.session import SessionLocal
from app.repositories import get_or_create_source


DEFAULT_SOURCES = [
    {
        "source_id": "byu_speeches_es",
        "name": "BYU Speeches Espanol",
        "source_type": "byu_speeches_es",
        "base_url": "https://speeches.byu.edu/spa/talks/",
        "language": "es",
        "crawl_strategy": "listing_and_talk_pages",
        "rate_limit": 30,
        "max_pages_per_run": 12,
        "robots_policy_notes": "Respetar robots.txt; crawl limitado a discursos publicos en espanol.",
    },
    {
        "source_id": "byu_speeches",
        "name": "BYU Speeches English",
        "source_type": "byu_speeches_en",
        "base_url": "https://speeches.byu.edu/talks/",
        "language": "en",
        "crawl_strategy": "listing_and_talk_pages",
        "rate_limit": 30,
        "max_pages_per_run": 12,
        "robots_policy_notes": "Respetar robots.txt; crawl limitado a discursos publicos.",
    },
    {
        "source_id": "discursos_sud",
        "name": "Discursos SUD",
        "source_type": "discursos_sud",
        "base_url": "https://discursosud.com/",
        "language": "es",
        "crawl_strategy": "wordpress_posts",
        "rate_limit": 20,
        "max_pages_per_run": 10,
        "robots_policy_notes": "Sitio no oficial; usar crawl lento, incremental y con deduplicacion estricta.",
    },
    {
        "source_id": "general_conference",
        "name": "Conferencia General",
        "source_type": "general_conference",
        "base_url": "https://www.churchofjesuschrist.org/study/general-conference",
        "language": "es",
        "crawl_strategy": "official_library_pages",
        "rate_limit": 20,
        "max_pages_per_run": 10,
        "robots_policy_notes": "Fuente oficial; respetar robots.txt y no descargar masivamente.",
    },
    {
        "source_id": "church_manuals",
        "name": "Manuales de la Iglesia",
        "source_type": "church_manuals",
        "base_url": "https://www.churchofjesuschrist.org/study/manual",
        "language": "es",
        "crawl_strategy": "official_library_pages",
        "rate_limit": 20,
        "max_pages_per_run": 10,
        "robots_policy_notes": "Fuente oficial; limitar paginas por corrida y evitar rutas de cuenta/media no necesarias.",
    },
    {
        "source_id": "joseph_smith_papers",
        "name": "Joseph Smith Papers",
        "source_type": "joseph_smith_papers",
        "base_url": "https://www.josephsmithpapers.org/",
        "language": "en",
        "crawl_strategy": "historical_documents",
        "rate_limit": 20,
        "max_pages_per_run": 8,
        "robots_policy_notes": "Fuente historica/documental; advertir que no es manual doctrinal oficial.",
    },
    {
        "source_id": "byu_rsc",
        "name": "BYU Religious Studies Center",
        "source_type": "byu_rsc",
        "base_url": "https://rsc.byu.edu/",
        "language": "en",
        "crawl_strategy": "book_article_pages",
        "rate_limit": 20,
        "max_pages_per_run": 8,
        "robots_policy_notes": "Fuente academica BYU; crawl limitado por articulos/libros publicos.",
    },
    {
        "source_id": "come_follow_me",
        "name": "Come, Follow Me",
        "source_type": "church_manuals",
        "base_url": "https://www.churchofjesuschrist.org/study/manual/come-follow-me",
        "language": "es",
        "crawl_strategy": "official_library_pages",
        "rate_limit": 20,
        "max_pages_per_run": 8,
        "robots_policy_notes": "Subcoleccion oficial de manuales; limitada y auditable.",
    },
    {
        "source_id": "teachings_presidents",
        "name": "Teachings of Presidents of the Church",
        "source_type": "church_manuals",
        "base_url": "https://www.churchofjesuschrist.org/study/manual/teachings-presidents",
        "language": "en",
        "crawl_strategy": "official_library_pages",
        "rate_limit": 20,
        "max_pages_per_run": 8,
        "robots_policy_notes": "Subcoleccion oficial de manuales; limitada y auditable.",
    },
    {
        "source_id": "scriptures",
        "name": "Escrituras",
        "source_type": "scriptures",
        "base_url": "https://www.churchofjesuschrist.org/study/scriptures",
        "language": "es",
        "crawl_strategy": "official_scripture_pages",
        "rate_limit": 20,
        "max_pages_per_run": 8,
        "robots_policy_notes": "Fuente oficial; no descargar masivamente capitulos sin aprobacion.",
    },
]


def seed_sources() -> None:
    with SessionLocal() as db:
        for item in DEFAULT_SOURCES:
            get_or_create_source(
                db,
                item["source_id"],
                item["name"],
                item["base_url"],
                source_type=item["source_type"],
                language=item["language"],
                crawl_strategy=item["crawl_strategy"],
                rate_limit=item["rate_limit"],
                max_pages_per_run=item["max_pages_per_run"],
                robots_policy_notes=item["robots_policy_notes"],
                config={
                    "sourceId": item["source_id"],
                    "sourceType": item["source_type"],
                    "language": item["language"],
                    "crawlStrategy": item["crawl_strategy"],
                    "rateLimit": item["rate_limit"],
                    "maxPagesPerRun": item["max_pages_per_run"],
                    "robotsPolicyNotes": item["robots_policy_notes"],
                    "indexing": {"mode": "index_later", "estimate_cost_before_embedding": True},
                },
            )
